### ISSUE TITLE
Tree for logs and throwables

### ISSUE THREAD

**Issue by auchri** [ypresto/TimberTreeUtils#7]
The current `CrashlyticsLogExceptionTree` sends log messages as exceptions to crashlytics.

I want a tree which reports throwables and also log messages:

```
if (mLogExclusionStrategy.shouldSkipLog(priority, tag, message, t)) {
    return;
 }

if (t != null) {
    Crashlytics.logException(t);
} else {
    String formattedMessage = LogMessageHelper.format(priority, tag, message);
    Crashlytics.log(formattedMessage);
}
```

**Comment by ypresto** [comment]
CrashlyticsLogExceptionTree is intended to send exception. Note that log()s are not sent until exception is sent.

Please use CrashlyticsLogTree to just log().
You can suppress logException() for certain case (i.e. `throwable == null`) by passing logExclusionStrategy to CrashlyticsLogExceptionTree.

**Comment by auchri** [comment]
> Note that log()s are not sent until exception is sent.

Normally someone is only interested in logs if an exception occurs.

> Please use CrashlyticsLogTree to just log().
> You can suppress logException() for certain case (i.e. throwable == null) by passing logExclusionStrategy to CrashlyticsLogExceptionTree.

That seems like an ugly workaround for a simple problem to me.

**Comment by ypresto** [comment]
Library behavior should not be changed for the specific case. logExclusionStrategy is intended to provide customize without hassle or modify.

You can use just **simple** code:

``` java
Timber.plant(CrashlyticsLogExceptionTree(Log.ERROR, (priority, tag, message, t) -> t == null));
```

**Comment by auchri** [comment]
The code is only simple if you use java 8 with lambda support or an external lib.

I just copied the class to my project and changed the code to https://github.com/ypresto/TimberTreeUtils/issues/7#issue-157986325
